#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 21 18:11:56 2021

@author: javi
"""

def factorial(n):
    if n==0 or n==1:
        return 1
    
    acumulador=1
    contador=1
    while contador<n:
        contador+=1
        acumulador*=contador #acumulador= acumulador * contador
       
    return acumulador

print(factorial(4))