#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  9 17:27:36 2021

@author: javi
"""

class Cilindro:
    def __init__(self, radio, altura):
        self.radio = radio
        self.altura = altura
        
    def calcular_volumen(self):
        